---
title: "assignment03"
author: "Alex Clegg"
date: "2/9/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r library,message = FALSE, echo=FALSE}
library(tidyverse)
library(readxl)
library(ggrepel)
```


```{r data, echo=FALSE, message=FALSE}
CA_commute <-read_excel("data/transportation-to-work-1.xlsx")

```


```{r Statewide Commutes}

CA_commute %>%
  filter(reportyear == "2008-2010") %>%
  filter(geotype == "CA") %>%
  filter(mode != "CARTOTAL") %>%
  ggplot(aes(x = mode_name, y = percent)) +
  geom_bar(stat = "identity") +
  labs(x = "Commuting Mode", y = "Percent", title = "How Californians Get to Work", 
       subtitle = "In 2008-2010 the vast majority of Californians got to work by driving alone") +
  theme_classic() +
  scale_y_continuous(limits = c(0,100)) +
  theme(axis.text.x = element_text(angle=45,hjust = 1,vjust = 1))

```


```{r non-Car Commuters by Region}
#total mode

CA_commute %>%
  filter(reportyear == "2008-2010") %>%
  filter(geotype == "RE") %>%
  filter(mode == "CARTOTAL") %>%
  group_by(region_name) %>%
  ggplot(aes(x = region_name, y = 100 - percent)) +
  geom_col() +
  labs(x = "Region", y = "Percent", title = "Non-Car Commuters in California", 
       subtitle = "While driving is the predominant mode some regions have a significant number of commuters not using cars") +
  theme_classic() +
  theme(axis.text.x = element_text(angle=45,hjust = 1,vjust = 1))

```


```{r Drove Alone vs Place Pop}

CA_commute %>%
  filter(reportyear == "2008-2010") %>%
  filter(mode == "CARTOTAL") %>%
  filter(geotype == "RE") %>%
  ggplot(aes(x = pop_total/1000, y = 100 - percent)) +
  geom_text_repel(aes(label = region_name)) +
  scale_x_log10() +
  labs(x = "Region Population (Thousands)", y = "Percent", title = "Non-Car Commuters in California", 
       subtitle = "Many people assume that higher populations lead to fewer car commuters, but that's not always true") +
  theme_classic() 
  
```



```{r SF vs Bay Area vs State}

CA_commute %>%
  filter(reportyear == "2008-2010") %>%
  filter(mode != "CARTOTAL") %>%
  filter(geoname == c("Los Angeles city", "San Francisco city")) %>%
  ggplot(aes(x = mode_name, y = percent, fill = geoname)) +
  geom_col(position = position_dodge2(preserve = "total")) +
   labs(x = "Region Population (Thousands)", y = "Percent", title = "Non-Car Commuters in California", 
       subtitle = "Many people assume that higher populations lead to fewer car commuters, but that's not always true") +
  theme(axis.text.x = element_text(angle=45,hjust = 1,vjust = 1))

```

